### ISSUE TITLE
`@__FILE__` and `@__DIR__` return "incorrect" path

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaComputing/pluto-vscode#23]
![image](https://user-images.githubusercontent.com/6144086/143429442-ecda6599-ae2b-45a1-bc33-b623cd0c9574.png)

Strictly not incorrect since that's the temp file that the extension uses if I understand correctly, but incorrect in the sense that the behaviour is different compared to Pluto in the browser.

This is on version `0.1.1`.

**Comment by fonsp** [comment]
Thanks! This should be fixable since we insert the `LineNumberNode`s ourselves 🌝

**Comment by pankgeorg** [comment]
I'll try to use the exact same file as VSCode uses, as @pfitzseb suggested in the first place. Hopefully this will solve both this and #22, if it works. Otherwise we'll have to do some `LineNumberNode` magic
