### ISSUE TITLE
How do I enable Dark Mode for pluto.jl vs code extension 

### ISSUE THREAD

**Issue by rud-lucien** [JuliaComputing/pluto-vscode#31]
Hi,

This is more of a question than an issue. I'm trying out the Pluto extension in vscode and wanted to know how to switch the notebook to dark mode in vscode. My vscode is set to dark theme but the Pluto extension is light (which is difficult for my eyes).

**Comment by pankgeorg** [comment]
Hey! Does it work if you set the system wide setting to dark?

**Comment by rud-lucien** [comment]
That's not working for me unfortunately. My system wide settings are set to dark.

**Comment by rud-lucien** [comment]
![Screenshot 2023-10-08 161542](https://github.com/JuliaComputing/pluto-vscode/assets/30354417/946571e3-b76e-48a8-b669-15180dd39b1a)

**Comment by pankgeorg** [comment]
Unfortunately this PR runs a quite old version of Pluto (15 days before the launch of the Dark Mode 😔). 

We'll try to update a more recent version, but there are quite a few conflicts (https://github.com/fonsp/Pluto.jl/pull/1493) so it may take some time.

**Comment by rud-lucien** [comment]
No worries... good to know. Thanks
