### ISSUE TITLE
Ability to open a notebook file

### ISSUE THREAD

**Issue by fonsp** [JuliaComputing/pluto-vscode#8]

**Comment by pankgeorg** [comment]
Implemented in #16, along with Pluto -> VSCode file flow.

**Comment by pankgeorg** [comment]
BUT what is not clear is how to open a _new_ notebook file

**Comment by pfitzseb** [comment]
Just add a `Pluto: Start new notebook` command?

**Comment by pankgeorg** [comment]
What I haven't implemented is how to save that new - dangling document. Working on it as we speak!
